name: Update Flex endpoint

on:
    workflow_dispatch: null
    push:
        branches:
            - main

defaults:
    run:
        shell: bash

jobs:
    call-flex-update:
        uses: symfony/recipes/.github/workflows/callable-flex-update.yml@main
        with:
            branch: main
            contrib: true
